library(tidyverse)   
library(skimr)       
library(paradox)
library(mlr3learners) 
library(mlr3measures) 
library(mlr3tuning)   
library(kknn)        
datos <- read.csv("diabetes.csv")
hist(diabdat$Pregnancies, xlab = "Embarazos", ylab = "Frecuencia", main = "Histograma de Embarazos")
hist(diabdat$Glucosa, xlab = "Glucosa", ylab = "Frecuencia", main = "Histograma de Glucosa")
hist(datos$PresionArterial, xlab = "Presión Arterial", ylab = "Frecuencia", main = "Histograma de Presión Arterial")
hist(datos$Grosor.de.Piel, xlab = "Grosor de Piel", ylab = "Frecuencia", main = "Histograma de Grosor de Piel")
hist(datos$Insulina, xlab = "Insulina", ylab = "Frecuencia", main = "Histograma de Insulina")
hist(diabdat$IMC, xlab = "IMC", ylab = "Frecuencia", main = "Histograma de Indice de Masa Corporal")
hist(datos$DiabetesPedigreeFunction, xlab = "DPF", ylab = "Frecuencia", main = "Diabetes Pedigree Function")
hist(diabdat$Edad, xlab = "Edad", ylab = "Frecuencia", main = "Histograma de Edad")
hist(datos$Diagnostico, xlab = "Diagnostico", ylab = "Frecuencia", main = "Histograma de Diagnostico")
x <- cor(datos, method = "pearson")
corrplot(x, method = "number", title = "Correlacion entre variables")
datos <- subset(datos, select = -c(PresionArterial, Insulina, DiabetesPedigreeFunction, Grosor.de.Piel))
datos <- mutate_at(datos,c("Diagnostico"), as.factor)
diabdat <- datos
robust_scalar <- function(x){(x-median(x))/(quantile(x,probs = .75)-quantile(x,probs= .25))}
diabdat <- subset(diabdat, select = -c(Diagnostico))
outliers <- function(data, lowLimit, highLimit){ 
              data[data < lowLimit] <- mean(data)
              data[data > highLimit] <- median(data)
              data}
diabdat$Pregnancies <- outliers(diabdat$Pregnancies, quantile(diabdat$Pregnancies, probs = 0.25)-(1.5*(quantile(diabdat$Pregnancies, probs = 0.75)-quantile(diabdat$Pregnancies, probs = 0.25))), quantile(diabdat$Pregnancies, probs = 0.75)+(1.5*(quantile(diabdat$Pregnancies, probs = 0.75)-quantile(diabdat$Pregnancies, probs = 0.25))))
diabdat$IMC <- outliers(diabdat$IMC, quantile(diabdat$IMC, probs = 0.25)-(1.5*(quantile(diabdat$IMC, probs = 0.75)-quantile(diabdat$IMC, probs = 0.25))), quantile(diabdat$IMC, probs = 0.75)+(1.5*(quantile(diabdat$IMC, probs = 0.75)-quantile(diabdat$IMC, probs = 0.25))))
diabdat$Edad <- outliers(diabdat$Edad, quantile(diabdat$Edad, probs = 0.25)-(1.5*(quantile(diabdat$Edad, probs = 0.75)-quantile(diabdat$Edad, probs = 0.25))), quantile(diabdat$Edad, probs = 0.75)+(1.5*(quantile(diabdat$Edad, probs = 0.75)-quantile(diabdat$Edad, probs = 0.25))))
diabdat <- as.data.frame(lapply(diabdat, standarize))
diabdat <- diabdat %>% mutate_each_(list(~scale(.) %>% as.vector), vars = c("Pregnancies","IMC","Edad","Glucosa"))
diabdat$Diagnostico <- datos$Diagnostico
str(diabdat)
tareadiab <- TaskClassif$new(id="clasif", backend=diabdat, target="Diagnostico")
atm <- lrn("classif.kknn")
atm$param_set
soluciones <- ParamSet$new(list(ParamInt$new("k",1,20), ParamInt$new("distance",1,3), ParamFct$new("kernel",c("rectangular","triangular","gaussian","inv","optimal")), ParamLgl$new("scale")))
busqueda <- mlr3tuning::tnr("grid_search")
vc <- rsmp("repeated_cv",folds=10,repeats=5)
ibusqueda <- TuningInstanceSingleCrit$new(task=tareadiab, learner = atm, resampling = vc, measure = msr("classif.acc"), search_space = soluciones, terminator=trm("none"))
future::plan("multisession")   
busqueda$optimize(ibusqueda)
ibusqueda$archive$best()
ggplot(ibusqueda$archive$data, aes(x=k,y=classif.acc,col=scale)) + geom_point(size=3)
ggplot(ibusqueda$archive$data, aes(x=k,y=classif.acc,col=kernel)) + geom_point(size=3)
ggplot(ibusqueda$archive$data, aes(x=k,y=classif.acc,col=distance)) + geom_point(size=3)
vcexterna<-rsmp("holdout", ratio=0.7) 
vcinterna<-rsmp("cv", folds=10)
optim.learner1<-AutoTuner$new(learner=atm,
                             vcinterna,msr("classif.acc"), 
                             soluciones,
                             terminator = trm("none"),
                             tuner=busqueda)
future::plan("multisession")
resultados1<-resample(tareadiab,optim.learner1,vcexterna)
resultados1$aggregate(measures=msr("classif.acc"))
modelo_final1<-optim.learner1$train(tareadiab)
prediccion<-modelo_final1$predict_newdata(diabdat)
confusion_matrix(truth = prediccion$truth, response=prediccion$response, positive = "1")
